//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizManagementSytemEntities : DbContext
    {
        private static QuizManagementSytemEntities _context;
        public QuizManagementSytemEntities()
            : base("name=QuizManagementSytemEntities")
        {
        }

        public static QuizManagementSytemEntities GetContext()
        {
            if (_context == null)
            {
                _context = new QuizManagementSytemEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Learner> Learner { get; set; }
        public virtual DbSet<LearnerResult> LearnerResult { get; set; }
        public virtual DbSet<Organizer> Organizer { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
